version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - . ./.ci/codebuild-git-plugin.sh
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$CI_GIT_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:CI_GIT_TAG
